### ISSUE TITLE
Documentation update acc-provision

### ISSUE THREAD

**Issue by headconnect** [noironetworks/aci-containers#219]
Hi,

It seems that there are quite a few possibilities that have not yet been documented (for instance kube_config).  Would it be possible for those to be included in provision/acc_provision/templates/provision-config.yaml

(or somewhere else)?

**Comment by snaiksat** [comment]
Are you asking if kube_config can be made a configuration option inside provision-config.yaml?

**Comment by headconnect** [comment]
It seems already to be a configuration option (with "allow_pods_kube_api_access" and similar options), but it's not documented in any easy-to-understand form.. for instance, it would be nice to know what "use_ds_rolling_update" actually does (even though it's likely just to flag some kubernetes yaml).

**Comment by FrederikSuijs** [comment]
I've asked the same question during CLEUR2019. Both to some of the engineers as to product management.
It would be nice if there is some more documenation about the acc_provison in general. Currently the script is more or less, take it or leave it, without too many options to tweak. Several objects are created automatically, which is good in a LAB environment, but some options are non-configurable. In an enterprise/production environment we made a naming convention, guidelines on how L3outs should be created, how an EPG is extended on a static path... All these things are not configurable at the moment. In my case I had to do some reverse engineering to find out what is exactly needed on the ACI fabric and tenant side, and provision this myself.
What I would be looking for is some more detail/documentation on what steps are exactly needed and which options are available. So for example instead of using the acc_provision script, existing automation tools can be leveraged to setup the whole shabang.

**Comment by snaiksat** [comment]
@headconnect Thanks for your comment. We try to document the existing options better.

**Comment by snaiksat** [comment]
@FrederikSuijs Thanks for your feedback. Per your comment - "In an enterprise/production environment we made a naming convention, guidelines on how L3outs should be created, how an EPG is extended on a static path... All these things are not configurable at the moment.", I would appreciate you if you can create separate issues outlining each requirement, and we can accordingly follow up (either implement or document) each one of those. Of course, at any point of time, please feel to add any enhancements to the implementation and/or docs.

**Comment by snaiksat** [comment]
acc-provision was moved out of the aci-containers repo.
